// Generated by gencpp from file messages/ButtonState.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_BUTTONSTATE_H
#define MESSAGES_MESSAGE_BUTTONSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct ButtonState_
{
  typedef ButtonState_<ContainerAllocator> Type;

  ButtonState_()
    : joystick(0)
    , button(0)
    , state(0)  {
    }
  ButtonState_(const ContainerAllocator& _alloc)
    : joystick(0)
    , button(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef uint8_t _joystick_type;
  _joystick_type joystick;

   typedef uint8_t _button_type;
  _button_type button;

   typedef uint8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::messages::ButtonState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::ButtonState_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonState_

typedef ::messages::ButtonState_<std::allocator<void> > ButtonState;

typedef boost::shared_ptr< ::messages::ButtonState > ButtonStatePtr;
typedef boost::shared_ptr< ::messages::ButtonState const> ButtonStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::ButtonState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::ButtonState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::ButtonState_<ContainerAllocator1> & lhs, const ::messages::ButtonState_<ContainerAllocator2> & rhs)
{
  return lhs.joystick == rhs.joystick &&
    lhs.button == rhs.button &&
    lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::ButtonState_<ContainerAllocator1> & lhs, const ::messages::ButtonState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messages::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ButtonState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ButtonState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d97fed8babddf36e3ba7a8b9236726be";
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd97fed8babddf36eULL;
  static const uint64_t static_value2 = 0x3ba7a8b9236726beULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/ButtonState";
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 joystick\n"
"uint8 button\n"
"uint8 state\n"
;
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::ButtonState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joystick);
      stream.next(m.button);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::ButtonState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::ButtonState_<ContainerAllocator>& v)
  {
    s << indent << "joystick: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joystick);
    s << indent << "button: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.button);
    s << indent << "state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_BUTTONSTATE_H
