// Generated by gencpp from file messages/Camera.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_CAMERA_H
#define MESSAGES_MESSAGE_CAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct Camera_
{
  typedef Camera_<ContainerAllocator> Type;

  Camera_()
    : port(0)
    , address()  {
    }
  Camera_(const ContainerAllocator& _alloc)
    : port(0)
    , address(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _port_type;
  _port_type port;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _address_type;
  _address_type address;





  typedef boost::shared_ptr< ::messages::Camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::Camera_<ContainerAllocator> const> ConstPtr;

}; // struct Camera_

typedef ::messages::Camera_<std::allocator<void> > Camera;

typedef boost::shared_ptr< ::messages::Camera > CameraPtr;
typedef boost::shared_ptr< ::messages::Camera const> CameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::Camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::Camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::messages::Camera_<ContainerAllocator1> & lhs, const ::messages::Camera_<ContainerAllocator2> & rhs)
{
  return lhs.port == rhs.port &&
    lhs.address == rhs.address;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::messages::Camera_<ContainerAllocator1> & lhs, const ::messages::Camera_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace messages

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::messages::Camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::Camera_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::Camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::Camera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5962e9b7032210cb9e9f696366c62cf3";
  }

  static const char* value(const ::messages::Camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5962e9b7032210cbULL;
  static const uint64_t static_value2 = 0x9e9f696366c62cf3ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/Camera";
  }

  static const char* value(const ::messages::Camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::Camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 port\n"
"string address\n"
;
  }

  static const char* value(const ::messages::Camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::Camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.port);
      stream.next(m.address);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::Camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::Camera_<ContainerAllocator>& v)
  {
    s << indent << "port: ";
    Printer<int32_t>::stream(s, indent + "  ", v.port);
    s << indent << "address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.address);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_CAMERA_H
