// Generated by gencpp from file messages/JoystickCommand.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_JOYSTICKCOMMAND_H
#define MESSAGES_MESSAGE_JOYSTICKCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct JoystickCommand_
{
  typedef JoystickCommand_<ContainerAllocator> Type;

  JoystickCommand_()
    : axisX(0.0)
    , axisY(0.0)  {
    }
  JoystickCommand_(const ContainerAllocator& _alloc)
    : axisX(0.0)
    , axisY(0.0)  {
  (void)_alloc;
    }



   typedef float _axisX_type;
  _axisX_type axisX;

   typedef float _axisY_type;
  _axisY_type axisY;





  typedef boost::shared_ptr< ::messages::JoystickCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::JoystickCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JoystickCommand_

typedef ::messages::JoystickCommand_<std::allocator<void> > JoystickCommand;

typedef boost::shared_ptr< ::messages::JoystickCommand > JoystickCommandPtr;
typedef boost::shared_ptr< ::messages::JoystickCommand const> JoystickCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::JoystickCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::JoystickCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'messages': ['/home/nvidia/SoftwareDevelopment/ROS/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::JoystickCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::JoystickCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::JoystickCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::JoystickCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::JoystickCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::JoystickCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::JoystickCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ef0f7484f7f056d7fcb586ad36e7d96";
  }

  static const char* value(const ::messages::JoystickCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ef0f7484f7f056dULL;
  static const uint64_t static_value2 = 0x7fcb586ad36e7d96ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::JoystickCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/JoystickCommand";
  }

  static const char* value(const ::messages::JoystickCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::JoystickCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 axisX\n\
float32 axisY\n\
";
  }

  static const char* value(const ::messages::JoystickCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::JoystickCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.axisX);
      stream.next(m.axisY);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JoystickCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::JoystickCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::JoystickCommand_<ContainerAllocator>& v)
  {
    s << indent << "axisX: ";
    Printer<float>::stream(s, indent + "  ", v.axisX);
    s << indent << "axisY: ";
    Printer<float>::stream(s, indent + "  ", v.axisY);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_JOYSTICKCOMMAND_H
