set(_CATKIN_CURRENT_PACKAGE "subscriber_test")
set(subscriber_test_VERSION "0.0.0")
set(subscriber_test_MAINTAINER "nvidia <nvidia@todo.todo>")
set(subscriber_test_PACKAGE_FORMAT "2")
set(subscriber_test_BUILD_DEPENDS "roscpp" "std_msgs" "power_distribution_panel")
set(subscriber_test_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(subscriber_test_BUILDTOOL_DEPENDS "catkin")
set(subscriber_test_BUILDTOOL_EXPORT_DEPENDS )
set(subscriber_test_EXEC_DEPENDS "roscpp" "std_msgs" "power_distribution_panel")
set(subscriber_test_RUN_DEPENDS "roscpp" "std_msgs" "power_distribution_panel")
set(subscriber_test_TEST_DEPENDS )
set(subscriber_test_DOC_DEPENDS )
set(subscriber_test_URL_WEBSITE "")
set(subscriber_test_URL_BUGTRACKER "")
set(subscriber_test_URL_REPOSITORY "")
set(subscriber_test_DEPRECATED "")