set(_CATKIN_CURRENT_PACKAGE "logic")
set(logic_VERSION "0.0.0")
set(logic_MAINTAINER "nvidia <nvidia@todo.todo>")
set(logic_PACKAGE_FORMAT "2")
set(logic_BUILD_DEPENDS "roscpp" "std_msgs")
set(logic_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(logic_BUILDTOOL_DEPENDS "catkin")
set(logic_BUILDTOOL_EXPORT_DEPENDS )
set(logic_EXEC_DEPENDS "roscpp" "std_msgs")
set(logic_RUN_DEPENDS "roscpp" "std_msgs")
set(logic_TEST_DEPENDS )
set(logic_DOC_DEPENDS )
set(logic_URL_WEBSITE "")
set(logic_URL_BUGTRACKER "")
set(logic_URL_REPOSITORY "")
set(logic_DEPRECATED "")