// Generated by gencpp from file messages/ButtonState.msg
// DO NOT EDIT!


#ifndef MESSAGES_MESSAGE_BUTTONSTATE_H
#define MESSAGES_MESSAGE_BUTTONSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace messages
{
template <class ContainerAllocator>
struct ButtonState_
{
  typedef ButtonState_<ContainerAllocator> Type;

  ButtonState_()
    : number(0)
    , state(0)  {
    }
  ButtonState_(const ContainerAllocator& _alloc)
    : number(0)
    , state(0)  {
  (void)_alloc;
    }



   typedef int32_t _number_type;
  _number_type number;

   typedef int32_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::messages::ButtonState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::messages::ButtonState_<ContainerAllocator> const> ConstPtr;

}; // struct ButtonState_

typedef ::messages::ButtonState_<std::allocator<void> > ButtonState;

typedef boost::shared_ptr< ::messages::ButtonState > ButtonStatePtr;
typedef boost::shared_ptr< ::messages::ButtonState const> ButtonStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::messages::ButtonState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::messages::ButtonState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'messages': ['/home/nvidia/SoftwareDevelopment/ROS/src/messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::messages::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::messages::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ButtonState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::messages::ButtonState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ButtonState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::messages::ButtonState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09160d212a568b0a18a64adb7eb7b9d1";
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09160d212a568b0aULL;
  static const uint64_t static_value2 = 0x18a64adb7eb7b9d1ULL;
};

template<class ContainerAllocator>
struct DataType< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "messages/ButtonState";
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::messages::ButtonState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 number \n\
int32 state\n\
";
  }

  static const char* value(const ::messages::ButtonState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::messages::ButtonState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ButtonState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::messages::ButtonState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::messages::ButtonState_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int32_t>::stream(s, indent + "  ", v.number);
    s << indent << "state: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MESSAGES_MESSAGE_BUTTONSTATE_H
