set(_CATKIN_CURRENT_PACKAGE "publisher_test")
set(publisher_test_VERSION "0.0.0")
set(publisher_test_MAINTAINER "nvidia <nvidia@todo.todo>")
set(publisher_test_PACKAGE_FORMAT "2")
set(publisher_test_BUILD_DEPENDS "roscpp" "std_msgs")
set(publisher_test_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(publisher_test_BUILDTOOL_DEPENDS "catkin")
set(publisher_test_BUILDTOOL_EXPORT_DEPENDS )
set(publisher_test_EXEC_DEPENDS "roscpp" "std_msgs")
set(publisher_test_RUN_DEPENDS "roscpp" "std_msgs")
set(publisher_test_TEST_DEPENDS )
set(publisher_test_DOC_DEPENDS )
set(publisher_test_URL_WEBSITE "")
set(publisher_test_URL_BUGTRACKER "")
set(publisher_test_URL_REPOSITORY "")
set(publisher_test_DEPRECATED "")