set(_CATKIN_CURRENT_PACKAGE "communication")
set(communication_VERSION "0.0.0")
set(communication_MAINTAINER "nvidia <nvidia@todo.todo>")
set(communication_PACKAGE_FORMAT "2")
set(communication_BUILD_DEPENDS "roscpp" "std_msgs" "message_generation" "messages")
set(communication_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs" "message_generation")
set(communication_BUILDTOOL_DEPENDS "catkin")
set(communication_BUILDTOOL_EXPORT_DEPENDS )
set(communication_EXEC_DEPENDS "roscpp" "std_msgs" "message_runtime" "messages")
set(communication_RUN_DEPENDS "roscpp" "std_msgs" "message_runtime" "messages" "message_generation")
set(communication_TEST_DEPENDS )
set(communication_DOC_DEPENDS )
set(communication_URL_WEBSITE "")
set(communication_URL_BUGTRACKER "")
set(communication_URL_REPOSITORY "")
set(communication_DEPRECATED "")